### ISSUE TITLE
运行frp_plugin_allowed_ports提示缺少libgo.so.19

### ISSUE THREAD

**Issue by MaHouyin** [Parmicciano/frp_plugin_allowed_ports#1]
/frp/frp_plugin_allowed_ports: error while loading shared libraries: libgo.so.19: cannot open shared object file: No such file or directory

Centos7.6，Centos8，Ubuntu18.04都这样提示

**Comment by Parmicciano** [comment]
Hi, 
If you don't fill the flag for the ports file, it will use the "ports" files in the same folder with no extension.
`rootCmd.PersistentFlags().StringVarP(&portsFile, "ports_file", "p", "./ports", "ports file")`
You can use your own file name with --p flag

**Comment by MaHouyin** [comment]
执行时加参数或者不加参数都会提示
 error while loading shared libraries: libgo.so.19: cannot open shared object file: No such file or directory

**Comment by MaHouyin** [comment]
我应该在哪里找到这个库文件放入lib目录，或者安装什么依赖环境？

**Comment by MaHouyin** [comment]
> Hi, If you don't fill the flag for the ports file, it will use the "ports" files in the same folder with no extension. `rootCmd.PersistentFlags().StringVarP(&portsFile, "ports_file", "p", "./ports", "ports file")` You can use your own file name with --p flag

执行时加参数或者不加参数都会提示
error while loading shared libraries: libgo.so.19: cannot open shared object file: No such file or directory
我应该在哪里找到这个库文件放入lib目录，或者安装什么依赖环境？

**Comment by Parmicciano** [comment]
Have. you run `go install`

**Comment by tecnicosya** [comment]
> Have. you run `go install`

Bad practice have a compiler in a production server
