### ISSUE TITLE
运行 -p 配置文件报错

### ISSUE THREAD

**Issue by MaHouyin** [Parmicciano/frp_plugin_allowed_ports#2]
运行    ./frp_plugin_allowed_ports  -p ./ports
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.ParseportsFromFile
        /home/ubuntu/frp_plugin_allowed_ports/cmd/frp_plugin_allowed_ports/cmd.go:68
main..go..func1
        /home/ubuntu/frp_plugin_allowed_ports/cmd/frp_plugin_allowed_ports/cmd.go:34
github_0com_1spf13_1cobra.Command.execute
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github_0com_1spf13_1cobra.Command.ExecuteC
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github_0com_1spf13_1cobra.Command.Execute
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.Execute
        /home/ubuntu/frp_plugin_allowed_ports/cmd/frp_plugin_allowed_ports/cmd.go:53
main.main
        /home/ubuntu/frp_plugin_allowed_ports/cmd/frp_plugin_allowed_ports/main.go:3
__start_context
        :0

配置文件ports内容

user1=65536
user2=80
user2=525
user1=6980
user2=subdomain
user1=subdomain2
user1=service.masternetwork.us

报错

**Comment by Parmicciano** [comment]
Are you sure there is no space after user1=service.masternetwork.us?
Already had a similar error

**Comment by MaHouyin** [comment]
> Are you sure there is no space after user1=service.masternetwork.us? Already had a similar error

没有空格

**Comment by tecufanujacu** [comment]
@Parmicciano I have the same error:

```
/tmp/frp_plugin_allowed_ports-linux-arm64 -p /tmp/portspanic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.ParseportsFromFile({0x7ff08a7e16?, 0x0?})
	/opt/frp_plugin_allowed_ports/cmd/frps_allowed_ports/cmd.go:68 +0x1cc
main.glob..func1(0xa00760?, {0x59b1c7?, 0x2?, 0x2?})
	/opt/frp_plugin_allowed_ports/cmd/frps_allowed_ports/cmd.go:34 +0x2c
github.com/spf13/cobra.(*Command).execute(0xa00760, {0x400001e190, 0x2, 0x2})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0xa00760)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.Execute()
	/opt/frp_plugin_allowed_ports/cmd/frps_allowed_ports/cmd.go:53 +0x24
main.main()
	/opt/frp_plugin_allowed_ports/cmd/frps_allowed_ports/main.go:4 +0x1c

```

Do you have some suggestion? Are you sure that the plugin works?
I'm trying to make the plugin work from two days.

**Comment by seekstar** [comment]
好像文件最后的换行符也不能有。。。
